# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from customLabel import customLabel

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1320, 760)
        Dialog.setMinimumSize(QtCore.QSize(1320, 760))
        self.pushButton_open_dir = QtWidgets.QPushButton(Dialog)
        self.pushButton_open_dir.setGeometry(QtCore.QRect(20, 20, 140, 26))
        self.pushButton_open_dir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_open_dir.setObjectName("pushButton_open_dir")
        # self.label = QtWidgets.QLabel(Dialog)
        self.label = customLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 70, 1131, 640))
        self.label.setMouseTracking(True)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_undo = QtWidgets.QPushButton(Dialog)
        self.pushButton_undo.setEnabled(False)
        self.pushButton_undo.setGeometry(QtCore.QRect(1170, 230, 140, 26))
        self.pushButton_undo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 725, 871, 26))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton_convert = QtWidgets.QPushButton(Dialog)
        self.pushButton_convert.setEnabled(True)
        self.pushButton_convert.setGeometry(QtCore.QRect(180, 20, 171, 26))
        self.pushButton_convert.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_convert.setAutoFillBackground(False)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.pushButton_auto_track = QtWidgets.QPushButton(Dialog)
        self.pushButton_auto_track.setEnabled(False)
        self.pushButton_auto_track.setGeometry(QtCore.QRect(1170, 260, 140, 26))
        self.pushButton_auto_track.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_auto_track.setObjectName("pushButton_auto_track")
        self.comboBox_class = QtWidgets.QComboBox(Dialog)
        self.comboBox_class.setEnabled(False)
        self.comboBox_class.setGeometry(QtCore.QRect(1170, 116, 140, 26))
        self.comboBox_class.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_class.setObjectName("comboBox_class")
        self.comboBox_class.addItem("")
        self.comboBox_class.addItem("")
        self.comboBox_class.addItem("")
        self.pushButton_add_class = QtWidgets.QPushButton(Dialog)
        self.pushButton_add_class.setEnabled(False)
        self.pushButton_add_class.setGeometry(QtCore.QRect(1170, 146, 140, 26))
        self.pushButton_add_class.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_add_class.setObjectName("pushButton_add_class")
        self.pushButton_next = QtWidgets.QPushButton(Dialog)
        self.pushButton_next.setEnabled(False)
        self.pushButton_next.setGeometry(QtCore.QRect(1070, 720, 80, 26))
        self.pushButton_next.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_prev = QtWidgets.QPushButton(Dialog)
        self.pushButton_prev.setEnabled(False)
        self.pushButton_prev.setGeometry(QtCore.QRect(980, 720, 80, 26))
        self.pushButton_prev.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_prev.setObjectName("pushButton_prev")
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setGeometry(QtCore.QRect(1170, 16, 140, 26))
        self.pushButton_save.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_load = QtWidgets.QPushButton(Dialog)
        self.pushButton_load.setEnabled(False)
        self.pushButton_load.setGeometry(QtCore.QRect(1170, 46, 140, 26))
        self.pushButton_load.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_load.setObjectName("pushButton_load")
        self.label_frame = QtWidgets.QLabel(Dialog)
        self.label_frame.setGeometry(QtCore.QRect(910, 720, 55, 26))
        self.label_frame.setObjectName("label_frame")
        self.comboBox_type = QtWidgets.QComboBox(Dialog)
        self.comboBox_type.setEnabled(False)
        self.comboBox_type.setGeometry(QtCore.QRect(1170, 80, 140, 26))
        self.comboBox_type.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.label_mouse_position = QtWidgets.QLabel(Dialog)
        self.label_mouse_position.setGeometry(QtCore.QRect(1024, 30, 111, 20))
        self.label_mouse_position.setObjectName("label_mouse_position")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setEnabled(False)
        self.listWidget.setGeometry(QtCore.QRect(1170, 300, 140, 440))
        self.listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_open_dir.setText(_translate("Dialog", "Open directory"))
        self.pushButton_undo.setText(_translate("Dialog", "Undo"))
        self.pushButton_convert.setText(_translate("Dialog", "Convert Video to images"))
        self.pushButton_auto_track.setText(_translate("Dialog", "Auto track"))
        self.comboBox_class.setItemText(0, _translate("Dialog", "White"))
        self.comboBox_class.setItemText(1, _translate("Dialog", "Yellow"))
        self.comboBox_class.setItemText(2, _translate("Dialog", "Red"))
        self.pushButton_add_class.setText(_translate("Dialog", "Add Class"))
        self.pushButton_next.setText(_translate("Dialog", "Next frame"))
        self.pushButton_prev.setText(_translate("Dialog", "Prev frame"))
        self.pushButton_save.setText(_translate("Dialog", "SAVE"))
        self.pushButton_load.setText(_translate("Dialog", "LOAD"))
        self.label_frame.setText(_translate("Dialog", "FRAME"))
        self.comboBox_type.setItemText(0, _translate("Dialog", "Point"))
        self.comboBox_type.setItemText(1, _translate("Dialog", "Box"))
        self.label_mouse_position.setText(_translate("Dialog", "0 / 0"))

